source	    "/usr/share/rvm/scripts/rvm"
source $(dirname $(gem which colorls))/tab_complete.sh

for file in ~/.zsh.d/{functions,src}/*.zsh; do
	[ -s "${file}" ] && source "${file}"
done
(cat ~/.cache/wal/sequences &)
