--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/z3r0/Personal/Pictures/Wallpaper/htb1.jpeg"

-- Special
background="#0F171C"
foreground="#9ec9d6"
cursor="#9ec9d6"

-- Colors
color0="#0F171C"
color1="#E80707"
color2="#689529"
color3="#B7BD3A"
color4="#F0AA35"
color5="#1F6B9E"
color6="#A961A7"
color7="#9ec9d6"
color8="#6e8c95"
color9="#E80707"
color10="#689529"
color11="#B7BD3A"
color12="#F0AA35"
color13="#1F6B9E"
color14="#A961A7"
color15="#9ec9d6"
