# Shell variables
# Generated by 'wal'
wallpaper='/home/z3r0/Personal/Pictures/Wallpaper/htb1.jpeg'

# Special
background='#0F171C'
foreground='#9ec9d6'
cursor='#9ec9d6'

# Colors
color0='#0F171C'
color1='#E80707'
color2='#689529'
color3='#B7BD3A'
color4='#F0AA35'
color5='#1F6B9E'
color6='#A961A7'
color7='#9ec9d6'
color8='#6e8c95'
color9='#E80707'
color10='#689529'
color11='#B7BD3A'
color12='#F0AA35'
color13='#1F6B9E'
color14='#A961A7'
color15='#9ec9d6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
