#!/usr/bin/env bash

killall -q polybar


while pgrep -x polybar >/dev/null; do sleep 2; done

# Launch top bar
polybar -c ~/.config/polybar/polybar-5/config.ini top 2> /dev/null &
polybar -c ~/.config/polybar/polybar-5/config.ini bottom 2> /dev/null &
