#!/bin/sh
#
#             _       _ _            
#       __  _(_)_ __ (_) |_ _ __ ___ 
#       \ \/ / | '_ \| | __| '__/ __|
#        >  <| | | | | | |_| | | (__ 
#       /_/\_\_|_| |_|_|\__|_|  \___|
#

# Mute speaker
amixer sset Speaker mute

# Set monitor if connected
$HOME/bin/externalMonitor

export PATH="$PATH:$HOME/bin"
# Load keybind
sxhkd &

# Start bspwm 
exec bspwm
