#! /bin/sh
#                                                                      
#  ▄▄                                                                   
#  ██                                                                   
#  ██▄███▄   ▄▄█████▄  ██▄███▄  ██      ██ ████▄██▄   ██▄████   ▄█████▄ 
#  ██▀  ▀██  ██▄▄▄▄ ▀  ██▀  ▀██ ▀█  ██  █▀ ██ ██ ██   ██▀      ██▀    ▀ 
#  ██    ██   ▀▀▀▀██▄  ██    ██  ██▄██▄██  ██ ██ ██   ██       ██       
#  ███▄▄██▀  █▄▄▄▄▄██  ███▄▄██▀  ▀██  ██▀  ██ ██ ██   ██       ▀██▄▄▄▄█ 
#  ▀▀ ▀▀▀     ▀▀▀▀▀▀   ██ ▀▀▀     ▀▀  ▀▀   ▀▀ ▀▀ ▀▀   ▀▀         ▀▀▀▀▀  
#                      ██                                               
#    
#                                     Config by: https://github.com/cOb4l7
#

. "${HOME}/.cache/wal/colors.sh"

# polybar
$HOME/.local/bin/barstart

# Check if the monitor is connected
if `xrandr -q | grep -q "HDMI1 connected"`
then
        # Set border color
        BLK="#111920"

        #
        # Monitor & Destop Settings
        # 

        bspc monitor LVDS1 -d 1 2 3 4 5 6
        bspc monitor HDMI1 -d 7 8 9
        bspc config -m LVDS1 window_gap           10
        bspc config -m LVDS1 border_width         1
        bspc config -m HDMI1 window_gap           10
        bspc config -m HDMI1 border_width         1

        #
        # Global Settings
        #

        bspc config -m LVDS1 normal_border_color   "$BLK"
        bspc config -m LVDS1 active_border_color   "$BLK"
        bspc config -m LVDS1 focused_border_color  "$BLK"
        bspc config -m LVDS1 urgent_border_color   "$BLK"
        bspc config -m LVDS1 presel_border_color   "$BLK"
        bspc config -m LVDS1 top_padding  35

	bspc config -m HDMI1 normal_border_color   "$BLK"
	bspc config -m HDMI1 active_border_color   "$BLK"
	bspc config -m HDMI1 focused_border_color  "$BLK"
	bspc config -m HDMI1 urgent_border_color   "$BLK"
	bspc config -m HDMI1 presel_border_color   "$BLK"
	bspc config -m HDMI1 top_padding  35

	bspc config normal_border_color "$color1"
        bspc config active_border_color "$color15"
        bspc config focused_border_color "$color2"
        bspc config urgent_border_color  "$BLK"
        bspc config presel_feedback_color "$color1"
else
        BLK="#101010"
        #
        # Monitor & Destop Settings
        # 

        bspc monitor LVDS1 -d Web Term FM Editor Social Git
        bspc config window_gap            10
        bspc config border_width          1
	bspc config -m LVDS1 normal_border_color   "$BLK"
	bspc config -m LVDS1 active_border_color   "$BLK"
	bspc config -m LVDS1 urgent_border_color   "$BLK"
	bspc config -m LVDS1 presel_border_color   "$BLK"
	bspc config -m LVDS1 top_padding 0
	bspc config -m LVDS1 bottom_padding 25

	#
        # Global Settings
        #

	bspc config normal_border_color "$color1"
	bspc config active_border_color "$color15"
        bspc config focused_border_color "$color2"
        bspc config urgent_border_color   "$BLK"
	bspc config presel_feedback_color "$color1"

fi

# Global Settings

bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner

bspc config focus_follows_pointer true
#  Rule Settings

# start apps in specific workspace
bspc rule -a Vivaldi-stable desktop='^1' follow=on state=floating rectangle=1364x700+0+0
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a code-oss desktop='^3' follow=on
bspc rule -a URxvt desktop='^4' follow=on
bspc rule -a Ncmpcpp desktop='^4' follow=on
bspc rule -a Ranger desktop='^4' follow=on state=floating rectangle=1065x538+150+84
bspc rule -a Newsboat desktop='^4' follow=on
bspc rule -a Neomutt desktop='^4' follow=on state=floating focus=on center=true rectangle=1080+240+150+40
bspc rule -a gitkraken desktop='^5' follow=on
bspc rule -a VirtualBox desktop='^6' follow=on state=floating focus=on
bspc rule -a mpv desktop='^6' follow=on state=floating focus=on rectangle=1364x700+0+0

# apps in float mode
bspc rule -a URxvt state=floating focus=on
bspc rule -a Nitrogen state=floating focus=on
bspc rule -a feh state=floating focus=on
bspc rule -a kitty state=floating focus=on
bspc rule -a Ncmpcpp state=floating focus=on
bspc rule -a Newsboat state=floating focus=on
bspc rule -a Ranger state=floating focus=on
#bspc rule -a Neomutt state=floating focus=on

#   Start Misc Programs

# picom
picom --experimental-backends
