#!/usr/bin/env bash

count=0
disconnected=""
disconnected1="!--!"
wireless_connected=""
ethernet_connected=""

SSID_NAME=$(iwgetid -r)
ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    wget -q --spider http://google.com
    if [ $? -eq 0 ]; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            echo "$wireless_connected" "${SSID_NAME}"; sleep 5
        fi
    else
        echo "$disconnected" "$disconnected1"; sleep 0.5
    fi
done
